# Outlines
#### 1. Data cleaning


In [1]:
# Packages for EDA
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
import plotly.express as px
import plotly.figure_factory as ff
from sklearn.ensemble import IsolationForest

In [2]:
df=pd.read_csv("googleplaystore.csv")
df.head()

App        Category  Rating  \
0     Photo Editor & Candy Camera & Grid & ScrapBook  ART_AND_DESIGN     4.1   
1                                Coloring book moana  ART_AND_DESIGN     3.9   
2  U Launcher Lite – FREE Live Cool Themes, Hide ...  ART_AND_DESIGN     4.7   
3                              Sketch - Draw & Paint  ART_AND_DESIGN     4.5   
4              Pixel Draw - Number Art Coloring Book  ART_AND_DESIGN     4.3   

  Reviews  Size     Installs  Type Price Content Rating  \
0     159   19M      10,000+  Free     0       Everyone   
1     967   14M     500,000+  Free     0       Everyone   
2   87510  8.7M   5,000,000+  Free     0       Everyone   
3  215644   25M  50,000,000+  Free     0           Teen   
4     967  2.8M     100,000+  Free     0       Everyone   

                      Genres      Last Updated         Current Ver  \
0               Art & Design   January 7, 2018               1.0.0   
1  Art & Design;Pretend Play  January 15, 2018               2.0.0   
2               Art & Design    August 1, 2018               1.2.4   
3               Art & Design      June 8, 2018  Varies with device   
4    Art & Design;Creativity     June 20, 2018                 1.1   

    Android Ver  
0  4.0.3 and up  
1  4.0.3 and up  
2  4.0.3 and up  
3    4.2 and up  
4    4.4 and up

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10841 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   App             10841 non-null  object 
 1   Category        10841 non-null  object 
 2   Rating          9367 non-null   float64
 3   Reviews         10841 non-null  object 
 4   Size            10841 non-null  object 
 5   Installs        10841 non-null  object 
 6   Type            10840 non-null  object 
 7   Price           10841 non-null  object 
 8   Content Rating  10840 non-null  object 
 9   Genres          10841 non-null  object 
 10  Last Updated    10841 non-null  object 
 11  Current Ver     10833 non-null  object 
 12  Android Ver     10838 non-null  object 
dtypes: float64(1), object(12)
memory usage: 1.1+ MB


### We need to
# ● Fix Rating
# ● Fix Size
# ● Fix Price
# ● Fix Category
# ● Fix Android Version
# ● Handle Missing Values
# ● Outlier Detection and Handling 


In [4]:
df.describe()

Rating
count  9367.000000
mean      4.193338
std       0.537431
min       1.000000
25%       4.000000
50%       4.300000
75%       4.500000
max      19.000000

In [5]:
df.duplicated().sum()


np.int64(483)

In [6]:
# Remove duplicated row
df.drop_duplicates(inplace=True)

### Fixing Size Coloumn

In [7]:
def convert_size(size):
    if pd.isna(size) or size.strip() == "":  
        return np.nan
    elif "M" in size:
        return float(size.replace("M", "")) 
    elif "K" in size:
        return float(size.replace("K", "")) / 1024   
    else:
        try:
            return float(size) 
        except ValueError:
            return np.nan  

df["Size"] = df["Size"].apply(convert_size)




In [8]:
df.Size.dtype

dtype('float64')

In [9]:
df['Size'].unique()

array([ 19. ,  14. ,   8.7,  25. ,   2.8,   5.6,  29. ,  33. ,   3.1,
        28. ,  12. ,  20. ,  21. ,  37. ,   2.7,   5.5,  17. ,  39. ,
        31. ,   4.2,   7. ,  23. ,   6. ,   6.1,   4.6,   9.2,   5.2,
        11. ,  24. ,   nan,   9.4,  15. ,  10. ,   1.2,  26. ,   8. ,
         7.9,  56. ,  57. ,  35. ,  54. ,   3.6,   5.7,   8.6,   2.4,
        27. ,   2.5,  16. ,   3.4,   8.9,   3.9,   2.9,  38. ,  32. ,
         5.4,  18. ,   1.1,   2.2,   4.5,   9.8,  52. ,   9. ,   6.7,
        30. ,   2.6,   7.1,   3.7,  22. ,   7.4,   6.4,   3.2,   8.2,
         9.9,   4.9,   9.5,   5. ,   5.9,  13. ,  73. ,   6.8,   3.5,
         4. ,   2.3,   7.2,   2.1,  42. ,   7.3,   9.1,  55. ,   6.5,
         1.5,   7.5,  51. ,  41. ,  48. ,   8.5,  46. ,   8.3,   4.3,
         4.7,   3.3,  40. ,   7.8,   8.8,   6.6,   5.1,  61. ,  66. ,
         8.4,  44. ,   1.6,   6.2,  53. ,   1.4,   3. ,   5.8,   3.8,
         9.6,  45. ,  63. ,  49. ,  77. ,   4.4,   4.8,  70. ,   6.9,
         9.3,   8.1,

### Handling missing values in Size

In [10]:
df["Size"] = df["Size"].fillna(df["Size"].median())


In [11]:
from datasist.structdata import detect_outliers
outliers_indices = detect_outliers(df, 0, ['Size'])
while len(outliers_indices) > 0:
        median_value = df['Size'].median()
        df.loc[outliers_indices, 'Size'] = median_value
        outliers_indices = detect_outliers(df,0,['Size'])


In [12]:
df['Size'].unique()

array([19. , 14. ,  8.7, 25. ,  2.8,  5.6,  3.1, 12. , 20. , 21. ,  2.7,
        5.5, 17. ,  4.2,  7. , 23. ,  6. ,  6.1,  4.6,  9.2,  5.2, 11. ,
       24. ,  9.4, 15. , 10. ,  1.2,  8. ,  7.9,  3.6,  5.7,  8.6,  2.4,
        2.5, 16. ,  3.4,  8.9,  3.9,  2.9,  5.4, 18. ,  1.1,  2.2,  4.5,
        9.8,  9. ,  6.7,  2.6,  7.1,  3.7, 22. ,  7.4,  6.4,  3.2,  8.2,
        9.9,  4.9,  9.5,  5. ,  5.9, 13. ,  6.8,  3.5,  4. ,  2.3,  7.2,
        2.1,  7.3,  9.1,  6.5,  1.5,  7.5,  8.5,  8.3,  4.3,  4.7,  3.3,
        7.8,  8.8,  6.6,  5.1,  8.4,  1.6,  6.2,  1.4,  3. ,  5.8,  3.8,
        9.6,  4.4,  4.8,  6.9,  9.3,  8.1,  2. ,  1.9,  1.8,  5.3,  7.6,
        9.7,  7.7,  6.3,  1.7,  1.3,  4.1,  1. ])

### Fixing price coloumn

In [13]:
df['Price'].unique()

array(['0', '$4.99', '$3.99', '$6.99', '$1.49', '$2.99', '$7.99', '$5.99',
       '$3.49', '$1.99', '$9.99', '$7.49', '$0.99', '$9.00', '$5.49',
       '$10.00', '$24.99', '$11.99', '$79.99', '$16.99', '$14.99',
       '$1.00', '$29.99', '$12.99', '$2.49', '$10.99', '$1.50', '$19.99',
       '$15.99', '$33.99', '$74.99', '$39.99', '$3.95', '$4.49', '$1.70',
       '$8.99', '$2.00', '$3.88', '$25.99', '$399.99', '$17.99',
       '$400.00', '$3.02', '$1.76', '$4.84', '$4.77', '$1.61', '$2.50',
       '$1.59', '$6.49', '$1.29', '$5.00', '$13.99', '$299.99', '$379.99',
       '$37.99', '$18.99', '$389.99', '$19.90', '$8.49', '$1.75',
       '$14.00', '$4.85', '$46.99', '$109.99', '$154.99', '$3.08',
       '$2.59', '$4.80', '$1.96', '$19.40', '$3.90', '$4.59', '$15.46',
       '$3.04', '$4.29', '$2.60', '$3.28', '$4.60', '$28.99', '$2.95',
       '$2.90', '$1.97', '$200.00', '$89.99', '$2.56', '$30.99', '$3.61',
       '$394.99', '$1.26', 'Everyone', '$1.20', '$1.04'], dtype=object)

In [14]:
def clean_price(price):
    if isinstance(price, str): 
        price = price.replace("$", "").strip()  
        if price.replace(".", "").isdigit(): 
            return float(price)
    return np.nan  

df["Price"] = df["Price"].apply(clean_price)


In [15]:
df['Price'].dtype

dtype('float64')

In [16]:
df['Price'].unique()

array([  0.  ,   4.99,   3.99,   6.99,   1.49,   2.99,   7.99,   5.99,
         3.49,   1.99,   9.99,   7.49,   0.99,   9.  ,   5.49,  10.  ,
        24.99,  11.99,  79.99,  16.99,  14.99,   1.  ,  29.99,  12.99,
         2.49,  10.99,   1.5 ,  19.99,  15.99,  33.99,  74.99,  39.99,
         3.95,   4.49,   1.7 ,   8.99,   2.  ,   3.88,  25.99, 399.99,
        17.99, 400.  ,   3.02,   1.76,   4.84,   4.77,   1.61,   2.5 ,
         1.59,   6.49,   1.29,   5.  ,  13.99, 299.99, 379.99,  37.99,
        18.99, 389.99,  19.9 ,   8.49,   1.75,  14.  ,   4.85,  46.99,
       109.99, 154.99,   3.08,   2.59,   4.8 ,   1.96,  19.4 ,   3.9 ,
         4.59,  15.46,   3.04,   4.29,   2.6 ,   3.28,   4.6 ,  28.99,
         2.95,   2.9 ,   1.97, 200.  ,  89.99,   2.56,  30.99,   3.61,
       394.99,   1.26,    nan,   1.2 ,   1.04])

In [17]:
df["Price"] = df["Price"].fillna(df["Price"].median())


In [18]:
df['Price'].unique()

array([  0.  ,   4.99,   3.99,   6.99,   1.49,   2.99,   7.99,   5.99,
         3.49,   1.99,   9.99,   7.49,   0.99,   9.  ,   5.49,  10.  ,
        24.99,  11.99,  79.99,  16.99,  14.99,   1.  ,  29.99,  12.99,
         2.49,  10.99,   1.5 ,  19.99,  15.99,  33.99,  74.99,  39.99,
         3.95,   4.49,   1.7 ,   8.99,   2.  ,   3.88,  25.99, 399.99,
        17.99, 400.  ,   3.02,   1.76,   4.84,   4.77,   1.61,   2.5 ,
         1.59,   6.49,   1.29,   5.  ,  13.99, 299.99, 379.99,  37.99,
        18.99, 389.99,  19.9 ,   8.49,   1.75,  14.  ,   4.85,  46.99,
       109.99, 154.99,   3.08,   2.59,   4.8 ,   1.96,  19.4 ,   3.9 ,
         4.59,  15.46,   3.04,   4.29,   2.6 ,   3.28,   4.6 ,  28.99,
         2.95,   2.9 ,   1.97, 200.  ,  89.99,   2.56,  30.99,   3.61,
       394.99,   1.26,   1.2 ,   1.04])

In [19]:
df["Price"].isna().sum()

np.int64(0)

### Fixing Rating coloumn

In [20]:
df['Rating'].unique()

array([ 4.1,  3.9,  4.7,  4.5,  4.3,  4.4,  3.8,  4.2,  4.6,  3.2,  4. ,
        nan,  4.8,  4.9,  3.6,  3.7,  3.3,  3.4,  3.5,  3.1,  5. ,  2.6,
        3. ,  1.9,  2.5,  2.8,  2.7,  1. ,  2.9,  2.3,  2.2,  1.7,  2. ,
        1.8,  2.4,  1.6,  2.1,  1.4,  1.5,  1.2, 19. ])

In [21]:
df["Rating"] = np.where(df["Rating"] > 5, df["Rating"].median(), df["Rating"])


### Handling missing values in rating

In [22]:
df["Rating"] = df["Rating"].fillna(df["Rating"].median())


In [23]:
df.Rating.describe()

count    10358.000000
mean         4.203746
std          0.485572
min          1.000000
25%          4.100000
50%          4.300000
75%          4.500000
max          5.000000
Name: Rating, dtype: float64

In [24]:
df["Rating"].isna().sum()

np.int64(0)

### Fix category

In [25]:
df['Category'].unique()

array(['ART_AND_DESIGN', 'AUTO_AND_VEHICLES', 'BEAUTY',
       'BOOKS_AND_REFERENCE', 'BUSINESS', 'COMICS', 'COMMUNICATION',
       'DATING', 'EDUCATION', 'ENTERTAINMENT', 'EVENTS', 'FINANCE',
       'FOOD_AND_DRINK', 'HEALTH_AND_FITNESS', 'HOUSE_AND_HOME',
       'LIBRARIES_AND_DEMO', 'LIFESTYLE', 'GAME', 'FAMILY', 'MEDICAL',
       'SOCIAL', 'SHOPPING', 'PHOTOGRAPHY', 'SPORTS', 'TRAVEL_AND_LOCAL',
       'TOOLS', 'PERSONALIZATION', 'PRODUCTIVITY', 'PARENTING', 'WEATHER',
       'VIDEO_PLAYERS', 'NEWS_AND_MAGAZINES', 'MAPS_AND_NAVIGATION',
       '1.9'], dtype=object)

In [26]:
df.loc[df["Category"] == "1.9", "Category"] = df["Category"].mode()[0]



In [27]:
df['Category'].isna().sum()

np.int64(0)

### Fixing Android Version



In [28]:

df['Android Ver'].unique()

array(['4.0.3 and up', '4.2 and up', '4.4 and up', '2.3 and up',
       '3.0 and up', '4.1 and up', '4.0 and up', '2.3.3 and up',
       'Varies with device', '2.2 and up', '5.0 and up', '6.0 and up',
       '1.6 and up', '1.5 and up', '2.1 and up', '7.0 and up',
       '5.1 and up', '4.3 and up', '4.0.3 - 7.1.1', '2.0 and up',
       '3.2 and up', '4.4W and up', '7.1 and up', '7.0 - 7.1.1',
       '8.0 and up', '5.0 - 8.0', '3.1 and up', '2.0.1 and up',
       '4.1 - 7.1.1', nan, '5.0 - 6.0', '1.0 and up', '2.2 - 7.1.1',
       '5.0 - 7.1.1'], dtype=object)

In [29]:

android_ver_mode = df['Android Ver'].mode()[0]
df['Android Ver'].replace({'Varies with device': android_ver_mode, None: android_ver_mode}, inplace=True)
df['Android Ver'].fillna(android_ver_mode, inplace=True)  


C:\Users\ebrah\AppData\Local\Temp\ipykernel_21044\3698808448.py:2: FutureWarning:

A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.





In [30]:
df['Android Ver'].unique()

array(['4.0.3 and up', '4.2 and up', '4.4 and up', '2.3 and up',
       '3.0 and up', '4.1 and up', '4.0 and up', '2.3.3 and up',
       '2.2 and up', '5.0 and up', '6.0 and up', '1.6 and up',
       '1.5 and up', '2.1 and up', '7.0 and up', '5.1 and up',
       '4.3 and up', '4.0.3 - 7.1.1', '2.0 and up', '3.2 and up',
       '4.4W and up', '7.1 and up', '7.0 - 7.1.1', '8.0 and up',
       '5.0 - 8.0', '3.1 and up', '2.0.1 and up', '4.1 - 7.1.1',
       '5.0 - 6.0', '1.0 and up', '2.2 - 7.1.1', '5.0 - 7.1.1'],
      dtype=object)

### Fixing Installs coloumn

In [31]:
df.Installs.unique()

array(['10,000+', '500,000+', '5,000,000+', '50,000,000+', '100,000+',
       '50,000+', '1,000,000+', '10,000,000+', '5,000+', '100,000,000+',
       '1,000,000,000+', '1,000+', '500,000,000+', '50+', '100+', '500+',
       '10+', '1+', '5+', '0+', '0', 'Free'], dtype=object)

In [32]:
df['Installs'] = df['Installs'].replace('Free', np.nan)

In [33]:
df['Installs'] = df['Installs'].str.replace(',', '')  # Remove commas
df['Installs'] = df['Installs'].str.replace('+', '')  # Remove '+'
df['Installs'] = pd.to_numeric(df['Installs'])  # Convert to integer

In [34]:
df['Installs'].unique()

array([1.e+04, 5.e+05, 5.e+06, 5.e+07, 1.e+05, 5.e+04, 1.e+06, 1.e+07,
       5.e+03, 1.e+08, 1.e+09, 1.e+03, 5.e+08, 5.e+01, 1.e+02, 5.e+02,
       1.e+01, 1.e+00, 5.e+00, 0.e+00,    nan])

In [35]:
df['Installs'] = df['Installs'].fillna(df['Installs'].median())

In [37]:
df['Installs'].unique()

array([1.e+04, 5.e+05, 5.e+06, 5.e+07, 1.e+05, 5.e+04, 1.e+06, 1.e+07,
       5.e+03, 1.e+08, 1.e+09, 1.e+03, 5.e+08, 5.e+01, 1.e+02, 5.e+02,
       1.e+01, 1.e+00, 5.e+00, 0.e+00])

### Fix Reviews Coloumn

In [38]:
df['Reviews'].unique()

array(['159', '967', '87510', ..., '603', '1195', '398307'],
      shape=(6002,), dtype=object)

In [39]:
df['Reviews'] = pd.to_numeric(df['Reviews'], errors='coerce')


In [40]:
df['Reviews'].unique()

array([1.59000e+02, 9.67000e+02, 8.75100e+04, ..., 6.03000e+02,
       1.19500e+03, 3.98307e+05], shape=(6002,))

In [41]:
df['Reviews'].dtype

dtype('float64')

In [42]:
df['Reviews'].isna().sum()

np.int64(1)

In [43]:
df['Reviews']=df['Reviews'].fillna(df['Reviews'].median())

In [44]:
df['Reviews'].unique()

array([1.59000e+02, 9.67000e+02, 8.75100e+04, ..., 6.03000e+02,
       1.19500e+03, 3.98307e+05], shape=(6001,))

### Analytical Questions:

### 1. What is the most expensive app on the Play Store?

In [45]:
most_expensive_app = df.loc[df['Price'].idxmax()]

most_expensive_app.App


"I'm Rich - Trump Edition"

### 2. Which genre has the highest number of apps?

In [46]:
genre_counts = df['Genres'].value_counts()

most_common_genre = genre_counts.idxmax()
most_common_genre

'Tools'

### 3. What is the average size of free vs. paid apps?

In [47]:


df['Type'] = df['Type'].replace('0', 'Free')
df['Type'] = df['Type'].fillna('Free')  
avg_size = df.groupby('Type')['Size'].mean()
(avg_size)


Type
Free    11.566236
Paid    11.096993
Name: Size, dtype: float64

### 4. What are the top 5 most expensive apps with a perfect rating (5)?

In [48]:

top_5_exp = df[(df['Rating'] == 5)].nlargest(5, 'Price')[['App']]
top_5_exp

App
5489                  AP Art History Flashcards
7477                 USMLE Step 2 CK Flashcards
5246                      Hey AJ! It's Bedtime!
5482                 meStudying: AP English Lit
7204  TI-84 CE Graphing Calculator Manual TI 84

### 5. How many apps have received more than 50K reviews?

In [49]:
apps_recieved = df[(df['Reviews'] >= 50000)].count()
apps_recieved.App





np.int64(2525)

### 6. What is the average price of apps, grouped by genre and number of installs?

In [50]:
avg_price = df.groupby(['Genres', 'Installs'])['Price'].mean().reset_index()

print(avg_price)

     Genres    Installs     Price
0    Action        10.0  0.000000
1    Action        50.0  0.663333
2    Action       100.0  1.096000
3    Action       500.0  0.000000
4    Action      1000.0  0.372500
..      ...         ...       ...
917    Word    100000.0  0.000000
918    Word   1000000.0  0.000000
919    Word   5000000.0  0.000000
920    Word  10000000.0  0.000000
921    Word  50000000.0  0.000000

[922 rows x 3 columns]


### 7. How many apps have a rating higher than 4.7, and what is their average price?

In [51]:
# Filter apps with a rating higher than 4.7
app_high_rating = df[df['Rating'] > 4.7]
num_high_rating_apps = app_high_rating['App'].count()
avg_high_price = app_high_rating['Price'].mean()
print(f"No. of apps with a rating higher than 4.7: {num_high_rating_apps}\nTheir average price: {avg_high_price:.2f}")


No. of apps with a rating higher than 4.7: 586
Their average price: 0.46


### 8. What is Google&#39;s estimated revenue from apps with 5,000,000+ installs?
(Assuming Google takes a 30% cut from app sales)

In [ ]:
high_installs_paid = df[(df['Installs'] >= 5000000) & (df['Type'] == 'Paid')]

total_revenue = (high_installs_paid['Price'] * high_installs_paid['Installs']).sum()

google_revenue = 0.30 * total_revenue

print(f"Total estimated revenue from apps with 5M+ installs: ${total_revenue:,.2f}")
print(f"Google's 30% cut: ${google_revenue:,.2f}")

Total estimated revenue from apps with 5M+ installs: $149,700,000.00
Google's 30% cut: $44,910,000.00


### 9. What are the maximum and minimum sizes of free vs. paid apps?

In [54]:
size_stats = df.groupby('Type')['Size'].agg(['min', 'max'])
size_stats

min   max
Type           
Free  1.0  25.0
Paid  1.0  25.0

### 10. Is there a correlation between an app’s rating, number of reviews, size, and its price?

In [61]:
import seaborn as sns
import matplotlib.pyplot as plt
corr_matrix = df[['Rating', 'Reviews', 'Size', 'Price']].corr()

corr_matrix

Rating   Reviews      Size     Price
Rating   1.000000  0.063462  0.039412 -0.019710
Reviews  0.063462  1.000000  0.069584 -0.009416
Size     0.039412  0.069584  1.000000 -0.033135
Price   -0.019710 -0.009416 -0.033135  1.000000

### 11. How many apps exist for each type (free/paid) across different content ratings?

In [ ]:
type_count = df.groupby(['Content Rating', 'Type']).size().unstack()
type_count

Type               Free   Paid
Content Rating                
Adults only 18+     3.0    NaN
Everyone         7720.0  662.0
Everyone 10+      345.0   32.0
Mature 17+        428.0   19.0
Teen             1094.0   52.0
Unrated             2.0    NaN


### 12. How many apps are compatible with Android version 4.x?

In [60]:
ver_4 = df[df['Android Ver'].str.startswith("4")].count()
print(ver_4[0])

7921


C:\Users\ebrah\AppData\Local\Temp\ipykernel_21044\892578992.py:2: FutureWarning:

Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`

